name: reusable - lint - files - *.yml, *.yaml
on:
  workflow_call:
jobs:
  yaml-lint:
    name: yaml lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_data: |
            extends: default
            rules:
              document-start: disable
              empty-lines:
                max-end: 1
              line-length: disable
              truthy:
                allowed-values: ["true", "false", "on"]
          file_or_dir: .
          strict: true
