name: reusable - lint - files - *.md
on:
  workflow_call:
jobs:
  markdown-lint:
    name: markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DavidAnson/markdownlint-cli2-action@v23
        with:
          globs: "**/*.md"
